### ISSUE TITLE
dev: Benchmark the difference in performance between generating the entire list of instructions for every opcode or running an (extensive) if/else to carefully choose instructions

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#268]

**Comment by abdelhamidbakhta** [comment]
Currently we build dynamically an array to store the function offset of each opcode. It is quite elegant because it enables us to add them individually, and have a more readable code. There is a section that handles the dynamic invocation of each opcode related function. However, this code might be greedy in terms of computation, and we should investigate other options to handle the mapping of opcodes and there function.

The possible options are:
1. keep as is, dynamic invocations: elegant, flexible, but slow
2. mega giant if / return pattern: somewhat non readable giant function, but maximal efficiency
3. use `dw` to build opcodes array and use this to do the dynamic `invoke`: something in between, but my intuition is that it terms of performance it will be closer to 1. than to 2.

I would not even try 3. and go directly with 2. and estimate the benefit in terms of computation steps / builtins

**Comment by Eikix** [comment]
Thanks a lot Abdel for this precise and comprehensive description 🔥

**Comment by abdelhamidbakhta** [comment]
Ok, @spapinistarkware the GOAT has spoken:

```text
I assume you are discussing how to do a "switch case" on opcode? Not really up to date with details, but what about a jump table, like:

tempvar offset =2+2*opcode
jmp rel offset
jmp op0
jmp op1
```

Let's try this approach!!!

**Comment by Eikix** [comment]
How does the jmp know what op0 mean, op1 mean etc.? As in, where should one write the location of op0 ?

**Comment by spapinistarkware** [comment]
You can define them as labels in the dame function, or as new functions, if you carefully manage the arguments as to not push again

**Comment by ClementWalter** [comment]
I'm on it
