### ISSUE TITLE
feat: make kakarot smart contract (zkEVM) an upgradable contract

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#284]
As part of the maintainability effort for Kakarot, we'd want the master Kakarot smart contract to be upgradable.

- For testnet, the address being owner for upgrade will be owned by the core team leaders
- For mainnet, the address having rights to upgrade Kakarot will be owned by a [governor account](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/modules/ROOT/pages/governance.adoc)

**Comment by Eikix** [comment]
To claim this issue, please propose an implementation plan:)!

**Comment by Eikix** [comment]
@TotalPizza is on it!

**Comment by TotalPizza** [comment]
> As part of the maintainability effort for Kakarot, we'd want the master Kakarot smart contract to be upgradable.
> 
>     * For testnet, the address being owner for upgrade will be owned by the core team leaders
> 
>     * For mainnet, the address having rights to upgrade Kakarot will be owned by a [governor account](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/docs/modules/ROOT/pages/governance.adoc)

Sorry, I overlooked this issue.

**My implementation plan is be pretty slim:**
Instead of deploying the Kakarot itself, we declare the contract and use it as an implementation for a proxy.
I'd use the standard OZ proxy [contract](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/upgrades/presets/Proxy.cairo).

**Regarding ownership on testnet:** 
I'd be against a multisig contract and rather integrate the OZ [access control](https://github.com/OpenZeppelin/cairo-contracts/tree/main/src/openzeppelin/access/accesscontrol) library in order to give team members access to upgrade the implementation.

**Comment by Eikix** [comment]
@TotalPizza is taking a break from contribution. He'll come back stronger soon hopefully 🤞🔥.

**Comment by Eikix** [comment]
I believe we shouldn't take too much time no, as after the cairo1 migration is coming soon
