### ISSUE TITLE
feat: propose an architecture diagram for Kakarot's RPC adapter backend 

### ISSUE THREAD

**Issue by Eikix** [sayajin-labs/kakarot#294]
# Feature Request

**Describe the Feature Request**

I think a good way to go about it would be to submit to the community some kind of architecture diagram/tech strategy of your ideal way of implementing it (when you're ready and have investigated enough).

in very simple terms, come up with a diagram, akin to this one for Kakarot, explaining the interactions between different parties

![image](https://user-images.githubusercontent.com/66871571/203793875-2efd507d-8fb9-46ab-8e84-b2338fae1429.png)

the only difference would basically be writing up a bit more of the signatures of different calls inside text boxes 
essentially it's simply starting the discussion, giving the first nudge

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
@etashhh will starting working on it next week (28th November onwards)

**Comment by etashhh** [comment]
Will be taking this issue, how do I request assignment?

**Comment by Eikix** [comment]
Assigned to you!

**Comment by etashhh** [comment]
Here's my first pass at visualizing the RPC adapter backend. It's basic but essentially the user will connect their wallet client to the RPC node. Any calls will go through this node in order to interact with Kakarot. Both [ethers-rs](https://github.com/gakonst/ethers-rs) and [starknet-rs](https://github.com/xJonathanLEI/starknet-rs) will be useful for parsing Ethereum types and translating to Kakarot-compatible calls as well as instantiating a Starknet-compatible account.

Open to discussion! I anticipate there are many ideas about how to best approach this.

Some example RPC adapter implementations:
- [Software Mansion's web-3 account](https://github.com/software-mansion-labs/web3-account) (no longer functional as of the latest Starknet and Cairo updates)
- [Acala Network's Acala EVM+ eth-rpc-adapter](https://github.com/AcalaNetwork/bodhi.js/tree/master/eth-rpc-adapter)

![RPC Adapter Diagram](https://user-images.githubusercontent.com/112415316/205397086-4fa84565-f278-46c6-8838-033c3c936aae.jpeg)
