### ISSUE TITLE
Complete integration tests coverage (solmate tests) for ERC721

### ISSUE THREAD

**Issue by matthieuauger** [sayajin-labs/kakarot#353]

**Comment by jobez** [comment]
I'll be working on this issue.

**Comment by ClementWalter** [comment]
The goal of this issue is to test a kakarot deployed Solmate's ERC721 against their test suite, to be found [here](https://github.com/transmissions11/solmate/blob/main/src/test/ERC721.t.sol).

Possible approaches are:
- copy/paste their test file and adapt it to python and our test runner
- try to use [forge differential testing](https://book.getfoundry.sh/forge/differential-ffi-testing) and run tests with `forge` (now included in the project)
